### ISSUE TITLE
manpage

### ISSUE THREAD

**Issue by Nilsonfsilva** [samyk/pwnat#21]
Hi!
Given Debian's packaging policy: any binary that doesn't have a manpage, you had to.

Therefore, a manpage is attached, which can be incorporated in the next release, if desired.

thank you!
[manpage_pwnat.txt](https://github.com/samyk/pwnat/files/8456082/manpage_pwnat.txt)

**Comment by samyk** [comment]
Thanks, if you want to produce a pull request then we can cut a release.

**Comment by Nilsonfsilva** [comment]
We can see yes. But for now I need you to make the release available here:
https://github.com/samyk/pwnat/releases
so you can finish packaging and move up to debian.
See if you can do this as soon as possible.
Thank you

**Comment by samyk** [comment]
I've updated the manpage and pushed it, as well and made a source code release.

**Comment by Nilsonfsilva** [comment]
As soon as it's available on the debian repositories, I'll let you know.

I will submit the sponsor, for correction.

Thank you!
