### ISSUE TITLE
Example error?

### ISSUE THREAD

**Issue by gabrielfarah** [samyk/pwnat#3]
When triying to run the example in Ubuntu 12.04
![screenshot from 2014-09-03 18 49 20](https://cloud.githubusercontent.com/assets/2722780/4143161/3498fc66-33c5-11e4-9e63-560e1dd8abdb.png)

![screenshot from 2014-09-03 18 51 49](https://cloud.githubusercontent.com/assets/2722780/4143164/4fca625e-33c5-11e4-8a84-d6d6cf163b04.png)

**Comment by chakmeshma** [comment]
you should enter http://localhost:8000 in your browser not http://www.localhost.com:8000
